import { Ubuntu_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/ui/StairTransition";

const UbuntuMono = Ubuntu_Mono({ subsets: ["latin"], weight: ["400", "700"],
  variable: '--font-UbuntuMono'
 });

export const metadata = {
  title: "Bijay Ghosh || Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={UbuntuMono.className}>
        <Header/>
        {/* <StairTransition/> */}
        {/* <PageTransition> */}

        {children}
        {/* </PageTransition> */}
        </body>
    </html>
  );
}
